CREATE TABLE IF NOT EXISTS mpa_info (
    id INTEGER PRIMARY KEY,
    rating VARCHAR
);

CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    releaseDate TIMESTAMP,
    mpa_id INTEGER,
    duration INTEGER,
    CONSTRAINT film_fk FOREIGN KEY (mpa_id) REFERENCES mpa_info (id)
);

CREATE TABLE IF NOT EXISTS genre_info (
      id INTEGER PRIMARY KEY,
      genre VARCHAR
);

CREATE TABLE IF NOT EXISTS genre (
     film_id BIGINT NOT NULL,
     genre_id INTEGER NOT NULL,
     CONSTRAINT pk_genre PRIMARY KEY (film_id, genre_id),
    CONSTRAINT genre_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT genre_fk2 FOREIGN KEY (genre_id) REFERENCES genre_info (id)
    );

CREATE TABLE IF NOT EXISTS users (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR NOT NULL,
     login VARCHAR NOT NULL,
     name VARCHAR,
     birthday TIMESTAMP
);

CREATE TABLE IF NOT EXISTS likes (
     film_id BIGINT NOT NULL,
     user_id BIGINT NOT NULL,
     PRIMARY KEY (user_id, film_id),
     CONSTRAINT like_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
     CONSTRAINT like_fk2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT NOT NULL references USERS,
    friend_id BIGINT NOT NULL references USERS,
    PRIMARY KEY (user_id, friend_id)
);

INSERT INTO genre_info (id, genre)
SELECT *
FROM (
         SELECT 1 AS id, 'Комедия' AS genre UNION ALL
         SELECT 2, 'Драма' UNION ALL
         SELECT 3, 'Мультфильм' UNION ALL
         SELECT 4, 'Триллер' UNION ALL
         SELECT 5, 'Документальный' UNION ALL
         SELECT 6, 'Боевик'
     ) AS new_data
WHERE NOT EXISTS (
        SELECT 1
        FROM genre_info g
    );

INSERT INTO mpa_info (id, rating)
SELECT * FROM (
                  SELECT 1 AS id, 'G' AS rating UNION ALL
                  SELECT 2, 'PG' UNION ALL
                  SELECT 3, 'PG-13' UNION ALL
                  SELECT 4, 'R' UNION ALL
                  SELECT 5, 'NC-17'
              ) AS new_data
WHERE NOT EXISTS (
        SELECT 1
        FROM mpa_info m
    );
