CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    releaseDate TIMESTAMP,
    duration INTEGER
);

CREATE TABLE IF NOT EXISTS genre (
    film_id BIGINT,
    genre VARCHAR,
    CONSTRAINT genre_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mpa (
     film_id BIGINT,
     rating VARCHAR,
     description VARCHAR,
     CONSTRAINT mpa_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR,
     login VARCHAR,
     name VARCHAR,
     birthday TIMESTAMP
);

CREATE TABLE IF NOT EXISTS likes (
     film_id BIGINT,
     user_id BIGINT,
     CONSTRAINT like_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
     CONSTRAINT like_fk2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT,
    friend_id BIGINT,
    friendship BOOL,
    CONSTRAINT friends_fk FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT friends_fk2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);